### ISSUE TITLE
Mac-前端装机不完全指南

### ISSUE THREAD

**Issue by isunyuan** [isunyuan/blog#2]
每年新系统出来以后，虽然直接更新就好了，但个人心里作用，一定要重装才感觉干净！
趁着周末，扬帆起航！
old: macOS Catalina 10.15.7  
new:  macOS Big Sur 11.1

**Comment by sohope** [comment]
# Setup1：[HomeBrew](https://brew.sh/index_zh-cn)

#### 官方安装
``` 
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```
鉴于网络环境问题，十有九个都会安装失败，可选择下述方案  

#### 中科大镜像
```
/bin/bash -c "$(curl -fsSL https://cdn.jsdelivr.net/gh/ineo6/homebrew-install/install.sh)"
```

静待安装完成……  

在终端（Terminal）执行，以检验是否安装正常
``` 
brew doctor
……
```

遇到问题解决问题，直到“Your system is ready to brew.”，确保安装无误。

**Comment by sohope** [comment]
# Setup1： Shell方案 - [iTerm2](https://iterm2.com) + [oh-my-zsh](https://ohmyz.sh/#install)

#### Install iTerm2

```
brew install iTerm2
```

OR

官方下载 [iTerm2 Download](https://iterm2.com)


#### Install oh-my-zsh
官方
```
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
```
由于网络被墙，443异常解决方案多样。 建议直接更换安装源至Gitee
```
sh -c "$(curl -fsSL https://gitee.com/shmhlsy/oh-my-zsh-install.sh/raw/master/install.sh)"
```
两者安装完成后，配置zsh为系统默认shell。
``` tsx
// 查看系统 shells
cat /etc/shells 

// 配置 zsh 为默认shell
chsh -s /bin/zsh

// 设置 theme
open ~/.zshrc
// 调整 ZSH_THEME="xxxx" 即可, 提前下载好心仪的主题
```

青菜萝卜，各有所好！ 对于Theme，自由选择 [more of them](https://github.com/ohmyzsh/ohmyzsh/wiki/External-themes)   

我喜欢极简风格，所以个人推荐 [Pi](https://github.com/ohmyzsh/ohmyzsh/wiki/External-themes#pi) & [lambda-gitster](https://github.com/ohmyzsh/ohmyzsh/wiki/External-themes#lambda-gitster)

终端和iTerm2颜色主题，使用系统的纯黑，添加背景图片和透明度之后，颜值也不赖！

**Comment by sohope** [comment]
# Setup3：[Git](https://git-scm.com) 
话不多说系列之一， 版本控制万年青！  
```
brew install git
```
系统git其版本较低，所以重新安装下！调整执行软件时调用优先度， 
``` ts
// 打开配置文件
open ~/.zshrc 
// 然后在最后一行添加，保存退出！
export PATH=$PATH:PATH 1:PATH 2:PATH 3:——:PATH N
```
Git config Global
``` ts
// user config
git config --global user.name "userName"
git config --global user.email "userEmail"

// create ssh key.  一路回车带闪电.
ssh-keygen -o

// ssh key 位置
cd ~/.ssh
```

``` ts
git --version
// git version 2.29.2
```

**Comment by sohope** [comment]
# Setup4: [NVM](https://github.com/nvm-sh/nvm) && [Node](https://nodejs.org/en/)

#### Install NVM
Node多版本管理神器
``` ts
// 搜索 nvm 
brew search nvm
// 安装 nvm
brew install nvm
```
安装完成后，因为环境问题，暂时无法直接使用 nvm
``` ts
open ~/.zshrc

// 写入
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

source ~/.zshrc OR 重启终端

nvm --version

// 0.37.2
 ```


#### Install Node
```
nvm install version

nvm use version
```


#### 配置源
``` ts
// npm 配置 淘宝源
npx nrm use taobao

// 切回 官方源
npx nrm use npm

// yarn 配置 淘宝源
yarn config set registry https://registry.npm.taobao.org -g

// yarn 配置 node-sass 
yarn config set sass_binary_site http://cdn.npm.taobao.org/dist/node-sass -g
```

**Comment by sohope** [comment]
# Setup5: 常用软件
到这一步，前端通用场景下的环境基本可用，Nginx、Docker…皆根据实际情况自行安装。  

软件各自随意！

**Comment by isunyuan** [comment]
over
